<?php

/**
 * @file
 * Contains group_counter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pw_group_counter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the group_counter module.
    case 'help.page.pw_group_counter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides parahraph group numbers with title and background') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function pw_group_counter_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__pw_group_counter' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_pw_counter_reference__pw_group_counter' => [
      'base hook' => 'field',
    ],

  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function pw_group_counter_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  switch ($bundle) {
    case 'pw_group_counter':
      // $variables['#attached']['library'][] = 'counters/counters';
  }
}

/**
 * Implements hook_preprocess_field().
 */
function pw_group_counter_preprocess_field(&$variables) {
  if ($variables['element']['#entity_type'] == 'paragraph') {
    if ($variables['element']['#bundle'] == 'pw_group_counter') {
      if ($variables['field_name'] == 'field_pw_title') {

        $num_array = $variables['element']['#object']->get('field_pw_title')->getValue();

      }
    }
  }
}



